name: 12baskets-FTP-Deploy-Action

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    steps:
    - uses: shivammathur/setup-php@v2
      with:
        php-version: '7.4'
    # - uses: actions/checkout@v2
    # - name: Install Composer Dependencies
    #   run: composer install --prefer-dist --no-dev --no-interaction
    # - name: Create deployment artifact
    #   run: tar -czf app.tar.gz --exclude=*.git --exclude=node_modules --exclude=tests *
    # - name: Copy .env
    #   run: php -r "file_exists('.env') || copy('.env.example', '.env');"
    # - name: Directory Permissions
    #   run: chmod -R 777 storage bootstrap/cache

  web-deploy:
    needs: build
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v2
    
    - name: FTP Deploy
      uses: SamKirkland/FTP-Deploy-Action@4.2.0
      with:
        server: http://sc802.whpservers.com
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        protocol: ftp
        server-dir: /domains/gradbook.app/public_html/12basket2/
